plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.slava.videotranslator'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.slava.videotranslator'
        minSdk 29
        targetSdk 35
        versionCode 4
        versionName '0.4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

configurations.configureEach {
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
    exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.mlkit:translate:17.0.3'
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
    implementation 'com.alphacephei:vosk-android:0.3.75@aar'
    implementation 'net.java.dev.jna:jna:5.18.1@aar'
}
